-- ✨ Generated by https://elm.land 🌈 --


module Pages exposing
    ( Model, Msg
    , init, update, subscriptions, view
    )

{-| Connects all pages together, and renders the
right one based on the current URL

@docs Model, Msg
@docs init, update, subscriptions, view

-}

import Browser
import Effect exposing (Effect)
import Html
import Pages.ALL_
import Pages.HOME_
import Pages.SignIn
import Route exposing (Route)
import Route.Path
import Shared
import Subscription exposing (Subscription)
import Url exposing (Url)


type alias Context params =
    { route : Route params
    , shared : Shared.Model
    }



-- INIT


type Model
    = Model_HOME_ Pages.HOME_.Model
    | Model_SignIn Pages.SignIn.Model
    | Model_ALL_ Pages.ALL_.Model


init : Url -> Shared.Model -> ( Model, Effect Msg )
init url shared =
    case Route.Path.fromUrl url of
        Route.Path.HOME_ ->
            handleInitForPage
                { init = Pages.HOME_.init
                , shared = shared
                , url = url
                , params = ()
                , toModel = Model_HOME_
                , toMsg = HOME_
                }

        Route.Path.SignIn ->
            handleInitForPage
                { init = Pages.SignIn.init
                , shared = shared
                , url = url
                , params = ()
                , toModel = Model_SignIn
                , toMsg = SignIn
                }

        Route.Path.ALL_ params ->
            handleInitForPage
                { init = Pages.ALL_.init
                , shared = shared
                , url = url
                , params = params
                , toModel = Model_ALL_
                , toMsg = ALL_
                }


handleInitForPage :
    { init : Context params -> ( pageModel, Effect pageMsg )
    , params : params
    , url : Url
    , shared : Shared.Model
    , toModel : pageModel -> Model
    , toMsg : pageMsg -> Msg
    }
    -> ( Model, Effect Msg )
handleInitForPage props =
    let
        ( model, effect ) =
            props.init
                { route = Route.fromUrl props.params props.url
                , shared = props.shared
                }
    in
    ( props.toModel model
    , effect
        |> Effect.map props.toMsg
    )



-- UPDATE


type Msg
    = HOME_ Pages.HOME_.Msg
    | SignIn Pages.SignIn.Msg
    | ALL_ Pages.ALL_.Msg


update :
    Url
    -> Shared.Model
    -> Msg
    -> Model
    -> ( Model, Effect Msg )
update url shared msg model =
    case ( Route.Path.fromUrl url, msg, model ) of
        ( Route.Path.HOME_, HOME_ pageMsg, Model_HOME_ pageModel ) ->
            handleUpdateForPage
                { update = Pages.HOME_.update
                , url = url
                , shared = shared
                , toModel = Model_HOME_
                , toMsg = HOME_
                , params = ()
                , pageModel = pageModel
                , pageMsg = pageMsg
                }

        ( Route.Path.SignIn, SignIn pageMsg, Model_SignIn pageModel ) ->
            handleUpdateForPage
                { update = Pages.SignIn.update
                , url = url
                , shared = shared
                , toModel = Model_SignIn
                , toMsg = SignIn
                , params = ()
                , pageModel = pageModel
                , pageMsg = pageMsg
                }

        ( Route.Path.ALL_ params, ALL_ pageMsg, Model_ALL_ pageModel ) ->
            handleUpdateForPage
                { update = Pages.ALL_.update
                , url = url
                , shared = shared
                , toModel = Model_ALL_
                , toMsg = ALL_
                , params = params
                , pageModel = pageModel
                , pageMsg = pageMsg
                }

        _ ->
            ( model
            , Effect.none
            )


handleUpdateForPage :
    { update : Context params -> pageMsg -> pageModel -> ( pageModel, Effect pageMsg )
    , url : Url
    , shared : Shared.Model
    , toModel : pageModel -> Model
    , toMsg : pageMsg -> Msg
    , params : params
    , pageModel : pageModel
    , pageMsg : pageMsg
    }
    -> ( Model, Effect Msg )
handleUpdateForPage props =
    let
        ( model, effect ) =
            props.update
                { route = Route.fromUrl props.params props.url
                , shared = props.shared
                }
                props.pageMsg
                props.pageModel
    in
    ( props.toModel model
    , effect
        |> Effect.map props.toMsg
    )



-- SUBSCRIPTIONS


subscriptions : Url -> Shared.Model -> Model -> Subscription Msg
subscriptions url shared model =
    case ( model, Route.Path.fromUrl url ) of
        ( Model_HOME_ pageModel, Route.Path.HOME_ ) ->
            handleSubscriptionsForPage
                { subscriptions = Pages.HOME_.subscriptions
                , url = url
                , params = ()
                , shared = shared
                , toMsg = HOME_
                , pageModel = pageModel
                }

        ( Model_HOME_ _, _ ) ->
            Subscription.none

        ( Model_SignIn pageModel, Route.Path.SignIn ) ->
            handleSubscriptionsForPage
                { subscriptions = Pages.SignIn.subscriptions
                , url = url
                , params = ()
                , shared = shared
                , toMsg = SignIn
                , pageModel = pageModel
                }

        ( Model_SignIn _, _ ) ->
            Subscription.none

        ( Model_ALL_ pageModel, Route.Path.ALL_ params ) ->
            handleSubscriptionsForPage
                { subscriptions = Pages.ALL_.subscriptions
                , url = url
                , params = params
                , shared = shared
                , toMsg = ALL_
                , pageModel = pageModel
                }

        ( Model_ALL_ _, _ ) ->
            Subscription.none


handleSubscriptionsForPage :
    { subscriptions : Context params -> pageModel -> Subscription pageMsg
    , url : Url
    , params : params
    , shared : Shared.Model
    , toMsg : pageMsg -> Msg
    , pageModel : pageModel
    }
    -> Subscription Msg
handleSubscriptionsForPage props =
    props.subscriptions
        { route = Route.fromUrl props.params props.url
        , shared = props.shared
        }
        props.pageModel
        |> Subscription.map props.toMsg



-- VIEW


view : Url -> Shared.Model -> Model -> Browser.Document Msg
view url shared model =
    case ( model, Route.Path.fromUrl url ) of
        ( Model_HOME_ pageModel, Route.Path.HOME_ ) ->
            handleViewForPage
                { view = Pages.HOME_.view
                , url = url
                , params = ()
                , shared = shared
                , toMsg = HOME_
                , pageModel = pageModel
                }

        ( Model_HOME_ _, _ ) ->
            "The route doesn't match the current page."
                |> viewErrorPage url shared

        ( Model_SignIn pageModel, Route.Path.SignIn ) ->
            handleViewForPage
                { view = Pages.SignIn.view
                , url = url
                , params = ()
                , shared = shared
                , toMsg = SignIn
                , pageModel = pageModel
                }

        ( Model_SignIn _, _ ) ->
            "The route doesn't match the current page."
                |> viewErrorPage url shared

        ( Model_ALL_ pageModel, Route.Path.ALL_ params ) ->
            handleViewForPage
                { view = Pages.ALL_.view
                , url = url
                , params = params
                , shared = shared
                , toMsg = ALL_
                , pageModel = pageModel
                }

        ( Model_ALL_ _, _ ) ->
            "The route doesn't match the current page."
                |> viewErrorPage url shared


handleViewForPage :
    { view : Context params -> pageModel -> Browser.Document pageMsg
    , url : Url
    , params : params
    , shared : Shared.Model
    , toMsg : pageMsg -> Msg
    , pageModel : pageModel
    }
    -> Browser.Document Msg
handleViewForPage props =
    props.view
        { route = Route.fromUrl props.params props.url
        , shared = props.shared
        }
        props.pageModel
        |> documentMap props.toMsg


viewErrorPage : Url -> Shared.Model -> String -> Browser.Document msg
viewErrorPage url shared problem =
    { title = "ERROR"
    , body = [ Html.text problem ]
    }



-- UTILS


documentMap : (msg1 -> msg2) -> Browser.Document msg1 -> Browser.Document msg2
documentMap fn doc =
    { title = doc.title
    , body = List.map (Html.map fn) doc.body
    }
