-- ✨ Generated by https://elm.land 🌈 --


module Route exposing (Route, fromUrl)

import Dict exposing (Dict)
import Route.Path
import Url exposing (Url)


{-| Represents the full URL for a page.

Similar to the Url type, but with type-safe parameters and
your query as a dictionary to make working with query parameters
a bit easier.

-}
type alias Route params =
    { params : params
    , path : Route.Path.Path
    , query : Dict String String
    , fragment : Maybe String
    , url : Url
    }


{-| Create a Route from a URL and parameters
-}
fromUrl : params -> Url -> Route params
fromUrl params url =
    { params = params
    , path = Route.Path.fromUrl url
    , query = createQueryDict url.query
    , fragment = url.fragment
    , url = url
    }


{-| Convert a Route into an absolute URL string.

**Note:** Works with both "Route" values and records with the path, query, and fragment
field. This is useful for creating type-safe links to other pages.

-}
toString :
    { route
        | path : Route.Path.Path
        , query : Dict String String
        , fragment : Maybe String
    }
    -> String
toString route =
    let
        queryString : String
        queryString =
            if Dict.isEmpty route.query then
                ""

            else
                "?"
                    ++ (Dict.toList route.query
                            |> List.map toQueryParamString
                            |> String.join "&"
                       )

        toQueryParamString : ( String, String ) -> String
        toQueryParamString ( key, value ) =
            if String.isEmpty value then
                Url.percentEncode key

            else
                Url.percentEncode key ++ "=" ++ Url.percentEncode value

        fragmentString : String
        fragmentString =
            case route.fragment of
                Nothing ->
                    ""

                Just fragment ->
                    "#" ++ Url.percentEncode fragment
    in
    Route.Path.toString route.path ++ queryString ++ fragmentString


createQueryDict : Maybe String -> Dict String String
createQueryDict query =
    case query of
        Nothing ->
            Dict.empty

        Just queryString ->
            let
                toPairs : String -> Maybe ( String, String )
                toPairs pair =
                    case String.split "=" pair of
                        key :: value :: [] ->
                            Maybe.map2 Tuple.pair
                                (Url.percentDecode key)
                                (Url.percentDecode value)

                        key :: [] ->
                            Maybe.map2 Tuple.pair
                                (Url.percentDecode key)
                                (Just "")

                        _ ->
                            Nothing
            in
            queryString
                |> String.split "&"
                |> List.filterMap toPairs
                |> Dict.fromList
