-- ✨ Generated by https://elm.land 🌈 --


module Route.Path exposing
    ( Path(..)
    , fromUrl, fromString
    , href, toString
    )

{-|

@docs Path
@docs fromUrl, fromString
@docs href, toString

-}

import Html
import Html.Attributes
import Url exposing (Url)


{-| A type-safe version of the URL's path
-}
type Path
    = HOME_
    | Dashboard
    | Login
    | Logout
    | OrganizationInit
    | SignUp
    | ALL_ { all_ : List String }


{-| Convert a URL path string to a Route.Path
-}
fromUrl : Url -> Path
fromUrl url =
    fromString url.path


{-| Convert a URL path string to a Route.Path
-}
fromString : String -> Path
fromString urlPath =
    case
        urlPath
            |> String.split "/"
            |> List.filter (String.isEmpty >> not)
    of
        [] ->
            HOME_

        "dashboard" :: [] ->
            Dashboard

        "login" :: [] ->
            Login

        "logout" :: [] ->
            Logout

        "organization-init" :: [] ->
            OrganizationInit

        "sign-up" :: [] ->
            SignUp

        all_ ->
            ALL_ { all_ = all_ }


{-| Convert a Route.Path into a URL path
-}
toString : Path -> String
toString path =
    case path of
        HOME_ ->
            toUrl []

        Dashboard ->
            toUrl [ "dashboard" ]

        Login ->
            toUrl [ "login" ]

        Logout ->
            toUrl [ "logout" ]

        OrganizationInit ->
            toUrl [ "organization-init" ]

        SignUp ->
            toUrl [ "sign-up" ]

        ALL_ { all_ } ->
            toUrl [ String.join "/" all_ ]


toUrl : List String -> String
toUrl segments =
    "/" ++ String.join "/" (List.filter (String.isEmpty >> not) segments)


{-| A helper function for using `Route.Path` with an HTML `<a>` tag

**Not using `elm/html`?** Use the `toString` function above to create your
own version of this function for your view library.

-}
href : Path -> Html.Attribute msg
href path =
    Html.Attributes.href (toString path)
